[project]
name = "sprout-browser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.3",
    "jupyter>=1.1.1",
    "marimo>=0.19.6",
    "sqlglot>=28.6.0",
    "streamlit>=1.53.1",
]
